# Generated by Django 5.2.4 on 2025-07-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnumber',
            options={'verbose_name': 'Admin Number', 'verbose_name_plural': 'Admin Numbers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
